---
services:
  arm64-test:
    build:
      context: .
      dockerfile: .docker/test-arm64/Dockerfile
    platform: linux/arm64
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - test_data:/var/lib
    ports:
      - "8000:8000"    # grillgauge
      - "9090:9090"    # Prometheus
    networks:
      - test
    environment:
      container: docker

volumes:
  test_data:

networks:
  test:
    driver: bridge
