---
- name: restart grillgauge
  systemd:
    name: grillgauge
    state: restarted
    daemon_reload: yes

- name: restart bluetooth-agent
  systemd:
    name: bluetooth-agent
    state: restarted
    daemon_reload: yes

- name: restart dashboard
  systemd:
    name: dashboard
    state: restarted
    daemon_reload: yes
